import pdb;pdb.set_trace()
x=[1,2,3]
y=3
z=9
sum=y+z
pdb.set_trace()                        # Set the trace to where you see issue is....then we will reach at python debugger.
sum1=x+y


print(sum)
print(sum1)





